In [1]:
import pandas as pd
import numpy as np
import re

In [9]:
# df = pd.read_csv('input/casos_hosp_uci_def_sexo_edad_provres.csv')
ccaa = pd.read_csv('input/ccaa.csv', sep = ';',encoding='latin1')
provincias =

In [10]:
ccaa

   cod                ISO1
0   AN           Andalucía
1   AR              Aragón
2   AS            Asturias
3   CN            Canarias
4   CB           Cantabria
5   CM  Castilla La Mancha
6   CL     Castilla y León
7   CT            Cataluña
8   EX         Extremadura
9   GA             Galicia
10  IB      Islas Baleares
11  RI            La Rioja
12  MD              Madrid
13  MC              Murcia
14  NC             Navarra
15  PV          País Vasco
16  VC            Valencia
17  CE               Ceuta
18  ML             Melilla